rules:
  - id: hardcoded-api-key-gemini
    patterns:
      - pattern-either:
          - pattern: api_key = "AIza..."
          - pattern: GOOGLE_API_KEY = "AIza..."
          - pattern: google_api_key = "AIza..."
    message: |
      Hardcoded API key detected. This is a critical security risk.
      Use environment variables instead:
      api_key = os.getenv("GOOGLE_API_KEY")
    severity: ERROR
    languages:
      - python
    metadata:
      category: security
      cwe: "CWE-798: Use of Hard-coded Credentials"
      owasp: A02:2021 – Cryptographic Failures

  - id: requests-missing-timeout
    patterns:
      - pattern-either:
          - pattern: requests.get(...)
          - pattern: requests.post(...)
          - pattern: requests.put(...)
          - pattern: requests.patch(...)
          - pattern: requests.delete(...)
      - pattern-not: requests.$METHOD(..., timeout=...)
    message: |
      HTTP request without timeout parameter can cause indefinite hangs.
      Add timeout: requests.get(url, timeout=10)
    severity: WARNING
    languages:
      - python
    metadata:
      category: security
      cwe: "CWE-400: Uncontrolled Resource Consumption"
